version: '3'

services:

  dig_etl_engine:
    volumes:
      - .:/app/dig-etl-engine
      - ${ETK_DIR_PATH}:/app/etk

  mydig_ws:
    volumes:
      - ${MYDIG_DIR_PATH}:/app/mydig-webservice
      - ${ETK_DIR_PATH}:/app/etk
#      - ${SPACY_DIR_PATH}:/app/spacy-ui

  rss_feed_crawler:
    volumes:
      - ${RSS_DIR_PATH}:/app
